_target_: app.frontend.streamlit_app_talk2knowledgegraphs
default_user: "talk2kg_user"
data_package_allowed_file_types:
  - "pdf"
endotype_allowed_file_types:
  - "pdf"
upload_data_dir: "app/backend/files"
openai_llms:
  - "gpt-4o-mini"
  - "gpt-4-turbo"
  - "gpt-3.5-turbo"
ollama_llms:
  - "llama3.2"
  - "llama3.1"
  - "gemma"
  - "mistral"
reasoning_subgraph_topk_nodes: 10
reasoning_subgraph_topk_nodes_min: 1
reasoning_subgraph_topk_nodes_max: 100
reasoning_subgraph_topk_edges: 10
reasoning_subgraph_topk_edges_min: 1
reasoning_subgraph_topk_edges_max: 100