_target_: app.frontend.streamlit_app_talk2knowledgegraphs
default_user: "talk2kg_user"
data_package_allowed_file_types:
  - "pdf"
multimodal_allowed_file_types:
  - "xls"
  - "xlsx"
upload_data_dir: "../files"
kg_name: "BioBridge-PrimeKG"
kg_node_types:
  - "gene/protein"
  - "molecular_function"
  - "cellular_component"
  - "biological_process"
  - "drug"
  - "disease"
# kg_nodes_path: "aiagents4pharma/talk2knowledgegraphs/tests/files/biobridge_nodes.parquet.gzip"
# kg_edges_path: "aiagents4pharma/talk2knowledgegraphs/tests/files/biobridge_edges.parquet.gzip"
kg_pyg_path: "aiagents4pharma/talk2knowledgegraphs/tests/files/biobridge_multimodal_pyg_graph.pkl"
kg_text_path: "aiagents4pharma/talk2knowledgegraphs/tests/files/biobridge_multimodal_text_graph.pkl"
openai_api_key: ${oc.env:OPENAI_API_KEY}
openai_llms:
  - "gpt-4o-mini"
  - "gpt-4-turbo"
  - "gpt-3.5-turbo"
openai_embeddings:
  - "text-embedding-ada-002"
  - "text-embedding-3-small"
ollama_llms:
  - "llama3.2:1b"
  - "llama3.2"
  - "llama3.1"
ollama_embeddings:
  - "nomic-embed-text"
default_embedding_model: "openai"
temperature: 0.1
streaming: False
reasoning_subgraph_topk_nodes: 15
reasoning_subgraph_topk_nodes_min: 1
reasoning_subgraph_topk_nodes_max: 50
reasoning_subgraph_topk_edges: 15
reasoning_subgraph_topk_edges_min: 1
reasoning_subgraph_topk_edges_max: 50
# Database configuration moved to configs/utils/database/milvus/default.yaml
# This frontend config now only contains frontend-specific settings