defaults:
  - _self_
  - agents/t2kg_agent: default
  - tools/named_entity_recognition: default
  - tools/subgraph_extraction: default
  - tools/subgraph_summarization: default
  - tools/graphrag_reasoning: default
  - app/frontend: default