# talk2aiagents4pharma
services:
  talk2aiagents4pharma:
    platform: linux/amd64
    image: virtualpatientengine/talk2aiagents4pharma:latest
    container_name: talk2aiagents4pharma
    ports:
      - "8501:8501"
    environment:
      - MILVUS_HOST=milvus-standalone
      - MILVUS_PORT=19530
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - milvus

volumes:

networks:
  milvus:
    external: true
    name: milvus