#talk2aiagents4pharma
services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama-server
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    # Add healthcheck to ensure the service is running properly
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/version"]
      interval: 30s
      timeout: 10s
      retries: 3
    # Start the Ollama server
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "ollama serve &
      sleep 10 &&
      ollama pull nomic-embed-text &&
      tail -f /dev/null"
    networks:
      - app-network

  talk2aiagents4pharma:
    image: virtualpatientengine/talk2aiagents4pharma:latest
    container_name: talk2aiagents4pharma
    ports:
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      - ollama
    restart: unless-stopped
    networks:
      - app-network

volumes:
  ollama_data:
    name: ollama_data

networks:
  app-network:
    name: app-network
