# Talk2AIAgents4pharma
networks:
  talk2aiagents4pharma:
    driver: bridge

services:
  talk2aiagents4pharma-app:
    image: virtualpatientengine/talk2aiagents4pharma:latest
    container_name: talk2aiagents4pharma
    ports:
      - "8501:8501"
    networks:
      - talk2aiagents4pharma
    depends_on:
      ollama:
        condition: service_healthy
    env_file:
      - .env # Load variables from .env file

  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: always
    networks:
      - talk2aiagents4pharma
    ports:
      - "11434:11434"
    command: >
      sh -c "ollama pull nomic-embed-text && ollama serve"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:11434"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s
