#talk2aiagents4pharma
services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    env_file:
      - .env
    entrypoint:
      [
        "/bin/sh",
        "-c",
        "ollama serve & sleep 3 && ollama pull nomic-embed-text && wait",
      ]

  talk2aiagents4pharma:
    image: anshinfo/talk2aiagents4pharma
    container_name: talk2aiagents4pharma
    restart: unless-stopped
    depends_on:
      - ollama
    ports:
      - "8501:8501"
    environment:
      - OLLAMA_API_BASE_URL=http://ollama:11434
    env_file:
      - .env
    networks:
      - app-network

volumes:
  ollama-data:

networks:
  app-network:
