_target_: talk2knowledgegraphs.tools.subgraph_summarization
openai_api_key: ${oc.env:OPENAI_API_KEY}
openai_llms:
  - "gpt-4o-mini"
  - "gpt-4-turbo"
  - "gpt-3.5-turbo"
ollama_llms:
  - "llama3.2"
  - "llama3.1"
  - "gemma"
  - "mistral"
temperature: 0.1
streaming: False
prompt_subgraph_summarization: >
  You are talk2knowledgegraphs agent, a helpful assistant in reasoning over biomedical knowledge graph.
  Your task is to summarize the extracted textualized subgraph to provide a concise and informative
  summary of the subgraph to be used for reasoning as subgraph context. You are responsible for
  highlighting the most important nodes and edges in the subgraph to respond to the user's question.

  Textualized Subgraph: {textualized_subgraph}
  Question: {input}