# talk2knowledgegraphs
services:
  talk2knowledgegraphs:
    platform: linux/amd64
    image: virtualpatientengine/talk2knowledgegraphs:latest
    container_name: talk2knowledgegraphs
    ports:
      - "8501:8501"
    environment:
      - MILVUS_HOST=milvus-standalone
      - MILVUS_PORT=19530
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - milvus

networks:
  milvus:
    external: true
    name: milvus
