services:
  ollama:
    image: "${OLLAMA_IMAGE:-ollama/ollama:latest}"
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "ollama serve"
    networks:
      - app-network

  talk2knowledgegraphs:
    platform: linux/amd64
    image: virtualpatientengine/talk2knowledgegraphs:latest
    container_name: talk2knowledgegraphs
    ports:
      - "8501:8501"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - app-network

volumes:
  ollama_data:

networks:
  app-network:
    external: true
    name: app-network
