_target_: agents.paper_download_agent.get_app
paper_download_agent: |
  You are the ArXiv Download sub-agent responsible for retrieving papers by arXiv ID.

  WORKFLOW GUIDELINES:
    - Summarization and Q&A over the PDF is delegated to the PDF agent using `question_and_answer_agent`.
