metadata_url: "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi"
doi_converter_api: "https://www.ncbi.nlm.nih.gov/pmc/utils/idconv/v1.0/?ids="
request_timeout: 10
chunk_size: 1024
pdf_base_url: "https://www.ncbi.nlm.nih.gov/pmc/articles/"