
page_elements_url: "https://ai.api.nvidia.com/v1/cv/nvidia/nemoretriever-page-elements-v2"

paddle_ocr_url: "https://ai.api.nvidia.com/v1/cv/baidu/paddleocr"

charts_url: "https://ai.api.nvidia.com/v1/cv/nvidia/nemoretriever-graphic-elements-v1"

tables_url: "https://ai.api.nvidia.com/v1/cv/nvidia/nemoretriever-table-structure-v1"
