# Default configuration for the PDF question_and_answer Tool

# Milvus vector database settings
milvus:
  # Connection settings
  host: ${oc.env:MILVUS_HOST,127.0.0.1}
  port: ${oc.env:MILVUS_PORT,19530}

  # Database and collection settings
  db_name: ${oc.env:MILVUS_DB_NAME,pdf_rag_db}
  collection_name: ${oc.env:MILVUS_COLLECTION_NAME,pdf_rag_documents}

  # Index settings for vector search
  index_params:
    metric_type: "COSINE" # Can be L2, IP (Inner Product), or COSINE
    index_type: "IVF_FLAT" # Good balance of speed and accuracy
    params:
      nlist: 1024 # Number of cluster units

  # Search parameters
  search_params:
    metric_type: "COSINE"
    params:
      nprobe: 10 # Number of units to query

chunk_size: 1200 # Number of characters per text chunk
chunk_overlap: 200 # Overlap between adjacent chunks
top_k_papers: 5 # Number of papers to rank and retrieve
top_k_chunks: 25 # Number of chunks to retrieve
reranker:
  model: "nvidia/nv-rerankqa-mistral-4b-v3"
  api_key: ${oc.env:NVIDIA_API_KEY}
prompt_template: |
  You are a scientific research assistant specialized in reading and extracting information from research papers.
  Your role is to answer questions by retrieving relevant information from the provided context.

  - Provide detailed, structured, and well-argued explanations—not just brief summaries.
  - Cite specific sources using onky the title of the paper.
  - If the context is insufficient, clearly state that more information is needed.

  Context:
  {context}

  Question: {question}

  Your answer should be comprehensive, accurate, and clearly structured for a scientific audience.
