_target_: talk2knowledgegraphs.tools.multimodal_subgraph_extraction
ollama_embeddings:
  - "nomic-embed-text"
temperature: 0.1
streaming: False

# PCST Algorithm Parameters
topk: 15
topk_e: 15
cost_e: 0.5
c_const: 0.01
root: -1
num_clusters: 1
pruning: "gw"
verbosity_level: 0

# Dynamic Hardware-Aware Configuration (NEW)
# Note: search_metric_type is now automatically set by DynamicLibraryLoader
# GPU Mode: Uses "IP" with normalized vectors
# CPU Mode: Uses "COSINE" with raw vectors

# GPU Detection and Performance Settings
gpu_detection:
  # Timeout for GPU detection command (seconds)  
  detection_timeout: 10
  
  # Log GPU detection results
  log_detection: true
  
  # Force CPU mode even if GPU is detected (for testing)
  # Uncomment the line below to force CPU mode:
  # force_cpu_mode: true

# Hardware-Specific Vector Processing
vector_processing:
  # Enable dynamic metric type selection based on hardware
  dynamic_metrics: true
  
  # Enable GPU vector normalization when using GPU with COSINE preference
  gpu_normalize_vectors: true
  
  # Log vector processing configuration
  log_vector_config: true

# Milvus Database Configuration (NEW - was missing!)
milvus_db:
  # Database connection settings
  host: ${oc.env:MILVUS_HOST,localhost}
  port: ${oc.env:MILVUS_PORT,19530}
  
  # Database and collection names
  database_name: ${oc.env:T2KG_MILVUS_DB_NAME,talk2knowledgegraphs}
  
  # Cache settings for edge index
  cache_edge_index_path: ${oc.env:T2KG_CACHE_PATH,./cache/edge_index.pkl}
  
  # Collection loading settings
  validate_collection_loading: true
  consistency_level: "Strong"
node_id_column: "node_id"
node_attr_column: "node_attr"
edge_src_column: "edge_src"
edge_attr_column: "edge_attr"
edge_dst_column: "edge_dst"
node_colors_dict:
  "gene/protein": "#6a79f7"
  "molecular_function": "#82cafc"
  "cellular_component": "#3f9b0b"
  "biological_process": "#c5c9c7"
  "drug": "#c4a661"
  "disease": "#80013f"

biobridge:
  # source: "aiagents4pharma/talk2knowledgegraphs/tests/files/ibd_biobridge_multimodal/"
  source: "/mnt/blockstorage/biobridge_multimodal/"
  node_type:
    - "gene/protein"
    - "molecular_function"
    - "cellular_component"
    - "biological_process"
    - "drug"
    - "disease"