_target_: talk2knowledgegraphs.tools.multimodal_subgraph_extraction
ollama_embeddings:
  - "nomic-embed-text"
temperature: 0.1
streaming: False
topk: 5
topk_e: 5
cost_e: 0.5
c_const: 0.01
root: -1
num_clusters: 1
pruning: "gw"
verbosity_level: 0
node_id_column: "node_id"
node_attr_column: "node_attr"
edge_src_column: "edge_src"
edge_attr_column: "edge_attr"
edge_dst_column: "edge_dst"
node_colors_dict:
  "gene/protein": "#6a79f7"
  "molecular_function": "#82cafc"
  "cellular_component": "#3f9b0b"
  "biological_process": "#c5c9c7"
  "drug": "#c4a661"
  "disease": "#80013f"

biobridge:
  # source: "aiagents4pharma/talk2knowledgegraphs/tests/files/ibd_biobridge_multimodal/"
  source: "/mnt/blockstorage/biobridge_multimodal/"
  node_type:
    - "gene/protein"
    - "molecular_function"
    - "cellular_component"
    - "biological_process"
    - "drug"
    - "disease"

# Configuration for Milvus
milvus_db:
  alias: "default"
  host: "localhost"
  port: "19530"
  uri: "http://localhost:19530"
  token: "root:Milvus"
  user: "root"
  password: "Milvus"
  database_name: "t2kg_primekg"
  collection_edges: "t2kg_primekg_edges"
  collection_nodes: "t2kg_primekg_nodes"
  collection_nodes_gene_protein: "t2kg_primekg_nodes_gene_protein"
  collection_nodes_molecular_function: "t2kg_primekg_nodes_molecular_function"
  collection_nodes_cellular_component: "t2kg_primekg_nodes_cellular_component
  collection_nodes_biological_process: "t2kg_primekg_nodes_biological_process"
  collection_nodes_drug: "t2kg_primekg_nodes_drug"
  collection_nodes_disease: "t2kg_primekg_nodes_disease"
