_target_: talk2knowledgegraphs.tools.multimodal_subgraph_extraction
ollama_embeddings:
  - "nomic-embed-text"
temperature: 0.1
streaming: False

# PCST Algorithm Parameters
topk: 15
topk_e: 15
cost_e: 0.5
c_const: 0.01
root: -1
num_clusters: 1
pruning: "gw"
verbosity_level: 0

# Hardware-Specific Vector Processing
vector_processing:
  # Enable dynamic metric type selection based on hardware
  dynamic_metrics: true

# Tool-specific configuration only
# Database configuration moved to configs/database/milvus/default.yaml
