# Enhanced PubMed Paper Download Configuration
# This configuration supports multiple PDF retrieval strategies

# Primary APIs
id_converter_url: "https://pmc.ncbi.nlm.nih.gov/tools/idconv/api/v1/articles"
oa_api_url: "https://www.ncbi.nlm.nih.gov/pmc/utils/oa/oa.fcgi"

# Alternative PDF Sources
europe_pmc_base_url: "https://europepmc.org/backend/ptpmcrender.fcgi"
pmc_page_base_url: "https://www.ncbi.nlm.nih.gov/pmc/articles"
direct_pmc_pdf_base_url: "https://pmc.ncbi.nlm.nih.gov/articles"

# URL Conversion for NCBI FTP links
ftp_base_url: "ftp://ftp.ncbi.nlm.nih.gov"
https_base_url: "https://ftp.ncbi.nlm.nih.gov"

# Request Configuration
request_timeout: 15 # Increased from 10 for reliability
chunk_size: 8192 # For PDF downloads

# Web Scraping Configuration
user_agent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"

# Retry and Rate Limiting (optional - for future use)
max_retries: 3
retry_delay: 2 # seconds
batch_size: 10 # number of papers to process before delay
batch_delay: 5 # seconds between batches

# Debug Configuration
log_response_preview_chars: 500 # chars to log from API responses
enable_detailed_logging: true
