name: Docker Hub Deployment

on:
  workflow_run:
    workflows: ["RELEASE"]
    types:
      - completed
  workflow_dispatch:

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      build_t2b: ${{ steps.filter.outputs.talk2biomodels }}
      build_t2s: ${{ steps.filter.outputs.talk2scholars }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensure all tags are fetched

      - name: Detect Changes
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            talk2biomodels:
              - 'aiagents4pharma/talk2biomodels/**'
            talk2scholars:
              - 'aiagents4pharma/talk2scholars/**'

  docker-build-t2b:
    needs: detect-changes
    if: needs.detect-changes.outputs.build_t2b == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensure all tags are fetched

      - name: Debug Git Tags
        run: git tag # Check if tags are available

      - name: Get Latest Tag Version
        id: version
        run: |
          TAG=$(git describe --tags --abbrev=0)
          if [ -z "$TAG" ]; then
            echo "Error: No tags found. Please create a tag and push it."
            exit 1
          fi
          echo "VERSION=$TAG" >> $GITHUB_ENV

      - name: Debug Version Tag
        run: echo "Using VERSION=${{ env.VERSION }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Talk2Biomodels
        uses: docker/build-push-action@v6
        with:
          file: aiagents4pharma/talk2biomodels/Dockerfile
          push: true
          tags: |
            virtualpatientengine/talk2biomodels:${{ env.VERSION }}
            virtualpatientengine/talk2biomodels:latest

  docker-build-t2s:
    needs: detect-changes
    if: needs.detect-changes.outputs.build_t2s == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensure all tags are fetched

      - name: Debug Git Tags
        run: git tag # Check if tags are available

      - name: Get Latest Tag Version
        id: version
        run: |
          TAG=$(git describe --tags --abbrev=0)
          if [ -z "$TAG" ]; then
            echo "Error: No tags found. Please create a tag and push it."
            exit 1
          fi
          echo "VERSION=$TAG" >> $GITHUB_ENV

      - name: Debug Version Tag
        run: echo "Using VERSION=${{ env.VERSION }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Talk2Scholars
        uses: docker/build-push-action@v6
        with:
          file: aiagents4pharma/talk2scholars/Dockerfile
          push: true
          tags: |
            virtualpatientengine/talk2scholars:${{ env.VERSION }}
            virtualpatientengine/talk2scholars:latest
