# This is a basic workflow to help you get started with GitHub Actions
name: TESTS Talk2KnowledgeGraphs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  pull_request_target:
    branches: [ main ]
    paths:
      - 'aiagents4pharma/talk2knowledgegraphs/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

# This workflow contains jobs covering linting and code coverage (along with testing).
jobs:
  pylint-windows-ubuntu-macos:
    # The type of runner that the job will run on
    name: pylint
    runs-on: ${{ matrix.os }}

    strategy:
        matrix:
            os: [windows-latest, ubuntu-latest, macos-13]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Cache files
        uses: actions/cache@v4
        with:
          path: |
            ${{env.pythonLocation}}/lib/python3.12/site-packages/*
          key: ${{ runner.os }}-pip

      # install requirements
      - name: Install the requirements
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          pip3 install --break-system-packages -r requirements.txt

      # pylint
      - name: Run pylint
        run: |
          pylint --disable=R0801,R0902,W0221,W0122 aiagents4pharma/talk2knowledgegraphs

  # code coverage job for macos
  code-cov-macos:
    name: code-coverage
    runs-on: ${{ matrix.os }}

    strategy:
        matrix:
          os: [macos-13]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Cache files
      uses: actions/cache@v4
      with:
        path: |
          ${{env.pythonLocation}}/lib/python3.12/site-packages/*
          /usr/share/ollama/.ollama/models/*
        key: ${{ runner.os }}-pip

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        pip3 install -r requirements.txt
        brew install ollama
        ollama serve &
        sleep 10
        ollama pull nomic-embed-text
        ollama pull gemma2:2b

    - name: Reading cached Ollama models
      run: |
        echo "Cache Hit Status - ${{ steps.cache.outputs.cache-hit }}"
        brew install ollama
        ollama serve &
        sleep 10
        cp -r /usr/share/ollama/.ollama/models/* ~/.ollama/models/
        ollama list

    - name: Run tests with coverage
      run: coverage run --include=aiagents4pharma/talk2knowledgegraphs/* -m pytest --cache-clear aiagents4pharma/talk2knowledgegraphs/tests/

    - name: Check coverage
      run: |
        coverage report -m
        TOTAL_COVERAGE=$(coverage report -m | awk 'END {print int($NF)}')
        if [[ $TOTAL_COVERAGE -ne 100 ]]; then
          echo "Code coverage is not 100%. Please check the coverage report."
          exit 1
        fi
      env:
        COVERAGE_FILE: './.coverage'

  # code coverage job for ubuntu
  code-cov-ubuntu:
    name: code-coverage
    runs-on: ${{ matrix.os }}

    strategy:
        matrix:
          os: [ubuntu-latest]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Cache files
      uses: actions/cache@v4
      with:
        path: |
          ${{env.pythonLocation}}/lib/python3.12/site-packages/*
          /usr/share/ollama/.ollama/models/*
        key: ${{ runner.os }}-pip

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        pip3 install -r requirements.txt
        curl -fsSL https://ollama.com/install.sh | sh
        ollama serve &
        sleep 10
        ollama pull nomic-embed-text
        ollama pull gemma2:2b

    - name: Reading cached Ollama models
      run: |
        echo "Cache Hit Status - ${{ steps.cache.outputs.cache-hit }}"
        curl -fsSL https://ollama.com/install.sh | sh
        ollama serve &
        sleep 10
        cp -r /usr/share/ollama/.ollama/models/* ~/.ollama/models/
        ollama list

    - name: Run tests with coverage
      run: coverage run --include=aiagents4pharma/talk2knowledgegraphs/* -m pytest --cache-clear aiagents4pharma/talk2knowledgegraphs/tests/

    - name: Check coverage
      run: |
        coverage report -m
        TOTAL_COVERAGE=$(coverage report -m | awk 'END {print int($NF)}')
        if [[ $TOTAL_COVERAGE -ne 100 ]]; then
          echo "Code coverage is not 100%. Please check the coverage report."
          exit 1
        fi
      env:
        COVERAGE_FILE: './.coverage'

  # code coverage job for windows
  code-cov-windows:
    name: code-coverage
    runs-on: ${{ matrix.os }}

    strategy:
        matrix:
          os: [windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Cache files
      uses: actions/cache@v4
      with:
        path: |
          ${{env.pythonLocation}}/lib/python3.12/site-packages/*
          /usr/share/ollama/.ollama/models/*
        key: ${{ runner.os }}-pip

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        pip3 install -r requirements.txt
        curl -L https://ollama.com/download/ollama-windows-amd64.zip -o ollama-windows-amd64.zip
        tar -xzf .\ollama-windows-amd64.zip
        start ollama serve
        sleep 10
        cmd /k ollama pull nomic-embed-text
        cmd /k ollama pull gemma2:2b

    - name: Reading cached Ollama models
      run: |
        echo "Cache Hit Status - ${{ steps.cache.outputs.cache-hit }}"
        curl -L https://ollama.com/download/ollama-windows-amd64.zip -o ollama-windows-amd64.zip
        tar -xzf .\ollama-windows-amd64.zip
        start ollama serve
        sleep 10
        cp -r /usr/share/ollama/.ollama/models/* ~/.ollama/models/
        ollama list

    - name: Run tests with coverage
      run: coverage run --include=aiagents4pharma/talk2knowledgegraphs/* -m pytest --cache-clear aiagents4pharma/talk2knowledgegraphs/tests/

    - name: Check coverage
      run: |
        coverage report -m
        # $TOTAL_COVERAGE=(& coverage report -m | Select-Object -Last 1) -replace "[^\d]"  # Extract the last line and remove non-numeric characters
        $TOTAL_COVERAGE=(& coverage report -m | Select-Object -Last 1)
        # split and extract the last element
        $TOTAL_COVERAGE=($TOTAL_COVERAGE -split " ")[-1]
        # remove non-numeric characters
        $TOTAL_COVERAGE=($TOTAL_COVERAGE -replace "[^\d]")
        # convert to int
        $TOTAL_COVERAGE=[int]$TOTAL_COVERAGE
        echo "Total coverage: $TOTAL_COVERAGE"
        if ($TOTAL_COVERAGE -ne 100) {
          Write-Host "Code coverage is not 100%. Please check the coverage report."
          exit 1
        }
      env:
        COVERAGE_FILE: './.coverage'
