name: TESTS Talk2Scholars

on:
  pull_request:
    branches: [main]
    paths:
      - "aiagents4pharma/talk2scholars/**"
  workflow_dispatch:

env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  ZOTERO_API_KEY: ${{ secrets.ZOTERO_API_KEY }}
  ZOTERO_USER_ID: ${{ secrets.ZOTERO_USER_ID }}

jobs:
  pylint:
    name: pylint-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Miniforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-version: "latest"
          python-version: 3.12

      - name: Cache conda environment
        id: cache-conda
        uses: actions/cache@v3
        with:
          path: ${{ env.CONDA }}/envs/talk2scholars-env
          key: ${{ runner.os }}-conda-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-conda-

      - name: Create conda environment
        if: steps.cache-conda.outputs.cache-hit != 'true'
        shell: bash -l {0}
        run: |
          conda update -n base -c defaults conda -y
          conda create -n talk2scholars-env -y python=3.12 pip pylint -c conda-forge
          conda activate talk2scholars-env
          pip install -r requirements.txt

      - name: Run pylint
        shell: bash -l {0}
        run: |
          conda activate talk2scholars-env
          pylint --disable=R0801,R0902,W0221,W0122 aiagents4pharma/talk2scholars

  code-coverage:
    name: code-coverage-${{ matrix.os }}
    needs: pylint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Miniforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-version: "latest"
          python-version: 3.12

      - name: Restore conda environment cache
        id: cache-conda
        uses: actions/cache@v3
        with:
          path: ${{ env.CONDA }}/envs/talk2scholars-env
          key: ${{ runner.os }}-conda-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-conda-

      - name: Install test dependencies
        shell: bash -l {0}
        run: |
          if [ ! -d "$CONDA/envs/talk2scholars-env" ]; then
            conda update -n base -c defaults conda -y
            conda create -n talk2scholars-env -y python=3.12 pip -c conda-forge
            conda activate talk2scholars-env
            pip install -r requirements.txt
          fi
          conda activate talk2scholars-env
          conda install -n talk2scholars-env -y pytest coverage faiss-cpu -c conda-forge

      - name: Run tests with coverage (Windows)
        if: matrix.os == 'windows-latest'
        shell: bash -l {0}
        run: |
          conda run -n talk2scholars-env coverage run --include=aiagents4pharma/talk2scholars/* -m pytest --cache-clear aiagents4pharma/talk2scholars/tests/

      - name: Run tests with coverage (Ubuntu/macOS)
        if: matrix.os != 'windows-latest'
        shell: bash -l {0}
        run: |
          conda activate talk2scholars-env
          coverage run --include=aiagents4pharma/talk2scholars/* -m pytest --cache-clear aiagents4pharma/talk2scholars/tests/

      - name: Check coverage (Windows)
        if: matrix.os == 'windows-latest'
        shell: bash -l {0}
        run: |
          conda run -n talk2scholars-env coverage report -m --fail-under=100

      - name: Check coverage (Ubuntu/macOS)
        if: matrix.os != 'windows-latest'
        shell: bash -l {0}
        run: |
          conda activate talk2scholars-env
          coverage report -m
          TOTAL_COVERAGE=$(coverage report -m | awk 'END {print int($NF)}')
          if [[ $TOTAL_COVERAGE -ne 100 ]]; then
            echo "Code coverage is not 100%. Please check the coverage report."
            exit 1
          fi
        env:
          COVERAGE_FILE: "./.coverage"

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report-${{ matrix.os }}
          path: .coverage
