# bioRxiv Paper Download Configuration
# Configuration for downloading bioRxiv papers with metadata

# Primary API
api_url: "https://api.biorxiv.org/details"

# PDF Download (Note: Not used directly, PDF URLs are constructed from DOI + version)
pdf_base_url: "https://www.biorxiv.org/content/10.1101/"

# Request Configuration
request_timeout: 15 # Increased for reliability
chunk_size: 8192 # For PDF downloads

# Web Request Configuration
user_agent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"

# Retry and Rate Limiting (optional - for future use)
max_retries: 3
retry_delay: 2 # seconds
batch_size: 10 # number of papers to process before delay
batch_delay: 5 # seconds between batches

# Debug Configuration
enable_detailed_logging: true
